@startuml Player

class Player {
    - name : string;
    - score : int;
    - throws : List<int>;
    - average : double;
    - first9Average : double;
    + Name : string;
    + Score : int;
    + Throws : List<int>;
    + Average : double;
    + First9Average : double;
    + Player(name: string, score: int)
    + Throw(points: int) : void
    + RegisterThrow(points: int) : void
}

@enduml
